name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Reposoyu klonla
        uses: actions/checkout@v3

      - name: Flask uygulamasını test et
        run: echo "Tests passed (örnek olarak)"

      - name: Sunucuya SSH ile bağlan ve uygulamayı deploy et
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd benim_projem || cd ~
            pkill -f app.py || true
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            nohup venv/bin/python app.py > output.log 2>&1 & disown
